### ISSUE TITLE
user-defined prefix not used for default bindings (only used for custom bindings)

### ISSUE THREAD

**Issue by hunter-** [hkupty/nvimux#9]
When I follow your instructions on setting up a config for using lua I find that only my user-defined commands utilize my user-defined prefix — all other commands use the default prefix, "<C-b>". 

replication steps:
NVIM: v0.2.1
nvimux config:  https://github.com/hunter-/dotfiles/blob/master/config/nvim/startup/plugins/nvimux.vim

**Comment by hkupty** [comment]
Hi, thanks for the issue.
Yes, you are correct. This was due to how lua is loaded. The PR i just merged fixes this behavior. Thanks for reporting.

Feel free to reopen the issue if the error persists. I tested here on my side and seems to be working fine, but if you encounter any other issues, don't refrain from posting.

Cheers,
Henry

**Comment by hunter-** [comment]
Sweet! Thank you, I certainly appreciate your work

**Comment by hunter-** [comment]
Hm, I'm now having somewhat the opposite issue — custom keybindings that are remap a key mapped to a default are overridden by the default. Eg, if I set `nvimux.bindings.bind_all{
  {'j', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
  {'l', ':NvimuxVerticalSplit', {'n', 'v', 'i', 't'}},
}`
and I call `:verbose map <C-b>j`, I see: `v  <C-Space>j  * <C-W><NL>`, not `v  <C-Space>s  * :NvimuxHorizontalSplit<CR>`
